[env]
TERM = "xterm-256color"

[general]
import = ["~/.config/alacritty/themes/gruvbox-dark.toml"]
live_config_reload = true

[terminal]
shell = { program = "/usr/bin/zsh" }

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
size = 16.0

[window]
startup_mode = "Maximized"
opacity = 0.6
padding = { x = 10, y = 10 }
decorations = "none"
decorations_theme_variant = "Light"

[cursor]
style = { shape = "block", blinking = "Always" }
