# Colors (Alabaster dark)

# Default colors
[colors.primary]
background = '#0e1415'
foreground = '#cecece'

# Cursor colors
[colors.cursor]
text = '#0e1415'
cursor = '#cd974b'

# Selection colors
[colors.selection]
text = '#000000'
background = '#293334'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#d2322d'
green   = '#6abf40'
yellow  = '#cd974b'
blue    = '#217ebc'
magenta = '#9b3596'
cyan    = '#178f79'
white   = '#cecece'

# Bright colors
[colors.bright]
black   = '#333333'
red     = '#c33c33'
green   = '#95cb82'
yellow  = '#dfdf8e'
blue    = '#71aed7'
magenta = '#cc8bc9'
cyan    = '#47bea9'
white   = '#ffffff'
