# Colors (Nordic dark)

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#222630'
# soft contrast background = = '#32302f'
foreground = '#eceff4'

# Normal colors
[colors.normal]
black   = '#222630'
red     = '#bf616a'
green   = '#a3be8c'
yellow  = '#ebcb8b'
blue    = '#5e81ac'
magenta = '#b48ead'
cyan    = '#8fbcbb'
white   = '#eceff4'
